name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build plugins
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends cmake ninja-build extra-cmake-modules tree

      - name: Install resources
        run: |
          mkdir resources/build
          pushd resources/build
          cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja
          sudo ninja install

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja
          ninja
          env DESTDIR=out ninja install
          tree out
